databases:
  - name: db.sqlite3
    databaseName: db.sqlite3


services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
